### PR TITLE
Add usage instructions and improve the package structure

### PR DESCRIPTION
**Pull request by fwcd**
This PR...
* adds installation and usage instructions to the `README.md`.
    * Once https://github.com/3b1b/manim/pull/609 gets merged, this whole process should become simpler anyway.
* renames the addon to `pptx_export` to prevent a naming collision with the `pptx` package.
* moves the addon script and template files into a subdirectory to make installation more convenient (the user can simply copy the `pptx_export` directory into his `manim/addons`).

### CODE REVIEW

**Comment by yoshiask** [comment]
Does this also work for installations of manim from the source code?

**Comment by fwcd** [comment]
Yep, it does.

**Comment by yoshiask** [comment]
Confirmed, works with no issues.

**Comment by yoshiask** [comment]
Thanks for contributing, it's a lot easier to install now!

**Pull request merged**
